class Champion:
    def __init__(self):
        self.id = None
        self.name = None
        self.alias = None
        self.title = None
        self.keywords = None

    def __str__(self):
        return f'{self.id} {self.name} {self.alias} {self.title} {self.keywords}'


def fetch_champion_list():
    import requests

    r = requests.get(
        url='https://game.gtimg.cn/images/lol/act/img/js/heroList/hero_list.js')
    hero_list = r.json()
    hero_list = hero_list['hero']
    champion_list = []
    for hero in hero_list:
        c = Champion()
        c.id = hero['heroId']
        c.name = hero['name']
        c.alias = hero['alias']
        c.title = hero['title']
        c.keywords = hero['keywords']
        champion_list.append(c)
    return champion_list


if __name__ == '__main__':
    # CHAMPION_KEYWORDS的值是由下面这段代码生成的
    cl = fetch_champion_list()
    o = {}
    for c in cl:
        o[c.id] = c.keywords.split(',')
    print(o)

CHAMPION_KEYWORDS = {'1': ['安妮', '黑暗之女', '火女', 'Annie', 'anni', 'heianzhinv', 'huonv', 'an', 'hazn', 'hn'],
                     '2': ['狂战士', '奥拉夫', 'kzs', 'alf', 'Olaf', 'kuangzhanshi', 'aolafu'],
                     '3': ['正义巨像', '加里奥', 'Galio', 'jla', 'zyjx', 'zhengyijuxiang', 'jialiao'],
                     '4': ['卡牌大师', '崔斯特', '卡牌', 'TwistedFate', 'kp', 'cst', 'kpds', 'kapaidashi', 'cuisite',
                           'kapai'],
                     '5': ['德邦总管', '德邦', '赵信', 'XinZhao', 'db', 'dbzg', 'zx', 'debangzongguan', 'debang',
                           'zhaoxin'], '6': ['无畏战车', '厄加特', 'ejt', 'wwzc', 'Urgot', 'wuweizhanche', 'ejiate'],
                     '7': ['诡术妖姬', '妖姬', '乐芙兰', 'Leblanc', 'lfl', 'yj', 'gsyj', 'guishuyaoji', 'yaoji',
                           'lefulan'], '8': ['猩红收割者', '吸血鬼', '弗拉基米尔', 'fljme', 'xxg', 'xhsgz', 'Vladimir',
                                             'xinghongshougezhe', 'xixiegui', 'fulajimier'],
                     '9': ['远古恐惧', '费德提克', '稻草人', 'FiddleSticks', 'yuangukongju', 'feidetike', 'daocaoren',
                           'dcr', 'fdtk', 'ygkj'],
                     '10': ['正义天使', '凯尔', '天使', 'ts', 'zyts', 'ke', 'Kayle', 'zhengyitianshi', 'kaier',
                            'tianshi'],
                     '11': ['无极剑圣', '易', '剑圣', 'js', 'y', 'wjjs', 'MasterYi', 'wujijiansheng', 'yi',
                            'jiansheng'],
                     '12': ['阿利斯塔', '牛头', '牛头酋长', '酋长', 'alisita', 'niutou', 'niutouqiuzhang', 'qiuzhang',
                            'Alistar', 'alst', 'nt', 'ntqz', 'qz'],
                     '13': ['符文法师', '瑞兹', 'Ryze', '光头', 'rz', 'fwfs', 'gt', 'fuwenfashi', 'ruizi', 'guangtou'],
                     '14': ['亡灵战神', '塞恩', '赛恩', 'se', 'wlzs', 'Sion', 'wanglingzhanshen', 'saien'],
                     '15': ['战争女神', '轮子妈', '希维尔', 'lzm', 'xwe', 'zzns', 'Sivir', 'zhanzhengnvshen', 'lunzima',
                            'xiweier'],
                     '16': ['众星之子', '索拉卡', '星妈', '奶妈', 'xm', 'nm', 'slk', 'zxzz', 'Soraka', 'zhongxingzhizi',
                            'suolaka', 'xingma', 'naima'],
                     '17': ['迅捷斥候', '提莫', 'timo', 'Teemo', 'tm', 'xjch', 'xunjiechihou', 'timo'],
                     '18': ['麦林炮手', '小炮', '崔丝塔娜', 'xp', 'cstn', 'mlps', 'Tristana', 'mailinpaoshou',
                            'xiaopao', 'cuisitana'],
                     '19': ['祖安怒兽', '沃里克', '狼人', 'lr', 'wlk', 'zans', 'Warwick', 'zuannushou', 'wolike',
                            'langren'],
                     '20': ['雪原双子', '努努和威朗普', '努努', '雪人', 'Nunu', 'nn', 'xr', 'xysz', 'mmhwlp',
                            'xueyuanshuangzi', 'nunuheweilangpu', 'nunu', 'xueren'],
                     '21': ['赏金猎人', '赏金', '厄运小姐', 'MF', 'MissFortune', 'sj', 'sjlr', 'eyxj', 'shangjinlieren',
                            'shangjin', 'eyunxiaojie'],
                     '22': ['艾希', '寒冰', '爱射', '艾射', '冰弓', 'Ashe', 'aixi', 'hanbing', 'aishe', 'aishe',
                            'binggong', 'ax', 'hb', 'as', 'bg'],
                     '23': ['蛮族之王', '蛮王', '泰达米尔', 'Tryndamere', 'tdme', 'mw', 'mzzw', 'manzuzhiwang',
                            'manwang', 'taidamier'],
                     '24': ['武器大师', '贾克斯', '武器', 'Jax', 'wq', 'jks', 'wqds', 'wuqidashi', 'jiakesi', 'wuqi'],
                     '25': ['堕落天使', '莫甘娜', 'MGN', 'dlts', 'Morgana', 'duoluotianshi', 'moganna'],
                     '26': ['时光守护者', '基兰', 'Zilean', 'jl', 'sgshz', '时光老人', '时光老头', 'shiguangshouhuzhe',
                            'jilan', 'shiguanglaoren', 'shiguanglaotou'],
                     '27': ['炼金术士', '辛吉德', '炼金', 'lj', 'xjd', 'ljss', 'Singed', 'lianjinshushi', 'xinjide',
                            'lianjin'],
                     '28': ['痛苦之拥', '伊芙琳', '寡妇', 'Evelynn', 'tongkuzhiyong', 'yifulin', 'guafu', 'gf', 'tkzy',
                            'yfl'],
                     '29': ['瘟疫之源', '图奇', '老鼠', 'Twitch', 'ls', 'tq', 'wyzy', 'wenyizhiyuan', 'tuqi', 'laoshu'],
                     '30': ['死亡颂唱者', '卡尔萨斯', '死歌', 'Karthus', 'sg', 'kess', 'swscz', 'siwangsongchangzhe',
                            'kaersasi', 'sige'],
                     '31': ['虚空恐惧', '科加斯', '大虫子', '虫子', 'Chogath', 'xukongkongju', 'kejiasi', 'dachongzi',
                            'chongzi', 'xkkj', 'kjs', 'dcz', 'cz'],
                     '32': ['阿木木', '木乃伊', '分头', '殇之木乃伊', '木木', '伤之木乃伊', 'amumu', 'munaiyi',
                            'fentou', 'shangzhimunaiyi', 'amm', 'szmny', 'mny', 'ft', 'mm', 'mumu'],
                     '33': ['披甲龙龟', '拉莫斯', '龙龟', 'lg', 'pjlg', 'lms', 'Rammus', 'pijialonggui', 'lamosi',
                            'longgui'],
                     '34': ['凤凰', '冰晶凤凰', '艾尼维亚', 'Anivia', 'fenghuang', 'bingjingfenghuang', 'ainiweiya',
                            'anwy', 'bjfh', 'fh'],
                     '35': ['恶魔小丑', '小丑', '沙扣', '沙口', '萨科', 'xc', 'emxc', 'sk', 'emoxiaochou', 'xiaochou',
                            'sake', 'Shaco'],
                     '36': ['祖安狂人', '蒙多医生', '蒙多', 'DrMundo', 'zuankuangren', 'mengduoyisheng', 'mengduo',
                            'md', 'mdys', 'zakr'],
                     '37': ['琴瑟仙女', '琴女', '娑娜', 'sn', 'qn', 'qsxn', 'Sona', 'qinsexiannv', 'qinnv', 'suona'],
                     '38': ['虚空行者', '卡萨丁', 'ksd', 'xkxz', 'Kassadin', 'xukongxingzhe', 'kasading'],
                     '39': ['刀锋舞者', '艾瑞莉娅', '女刀', '女刀锋', 'Irelia', 'nd', 'ndf', 'dfwz', 'arly',
                            'daofengwuzhe', 'airuiliya', 'nvdao', 'nvdaofeng'],
                     '40': ['风暴之怒', '迦娜', '风女', 'fn', 'jn', 'fbzn', 'Janna', 'fengbaozhinu', 'jiana', 'fengnv'],
                     '41': ['海洋之灾', '普朗克', '船长', 'plk', 'cz', 'hyzz', 'Gangplank', 'haiyangzhizai', 'pulangke',
                            'chuanzhang'],
                     '42': ['英勇投弹手', '库奇', '飞机', 'Corki', 'yingyongtoudanshou', 'kuqi', 'feiji', 'fj', 'kq',
                            'yytds'],
                     '43': ['天启者', '卡尔玛', '扇子妈', 'Karma', 'szm', 'kem', 'tqz', 'tianqizhe', 'kaerma',
                            'shanzima'],
                     '44': ['瓦洛兰之盾', '塔里克', '宝石', 'bs', 'tlk', 'wllzd', 'Taric', 'waluolanzhidun', 'talike',
                            'baoshi'],
                     '45': ['邪恶小法师', '小法师', '维迦', 'xfs', 'xexfs', 'wj', 'Veigar', 'xieexiaofashi',
                            'xiaofashi', 'weijia'],
                     '48': ['巨魔之王', '巨魔', '特朗德尔', 'Trundle', 'jm', 'jmzw', 'tlde', 'jumozhiwang', 'jumo',
                            'telangdeer'],
                     '50': ['诺克萨斯统领', '乌鸦', '斯维因', 'swy', 'wy', 'nksstl', 'Swain', 'nuokesasitongling',
                            'wuya', 'siweiyin'],
                     '51': ['皮城女警', '凯特琳', '女警', '皮城', 'Caitlyn', 'pichengnvjing', 'kaitelin', 'nvjing',
                            'picheng', 'pc', 'nj', 'pcnj', 'ctl'],
                     '53': ['蒸汽机器人', '布里茨', '机器人', 'Blitzcrank', 'zhengqijiqiren', 'bulici', 'jiqiren',
                            'zqjqr', 'jqr', 'blc'],
                     '54': ['熔岩巨兽', '墨菲特', '石头人', 'Malphite', 'str', 'mft', 'ryjs', 'rongyanjushou',
                            'mofeite', 'shitouren'],
                     '55': ['不祥之刃', '卡特琳娜', '卡特', 'kt', 'ktln', 'bxzr', '不详', 'bx', 'Katarina',
                            'buxiangzhiren', 'katelinna', 'kate', 'buxiang'],
                     '56': ['永恒梦魇', '魔腾', 'noc', 'Nocturne', '梦魇', 'my', 'yhmy', 'mt', 'yonghengmengyan',
                            'moteng', 'mengyan'],
                     '57': ['扭曲树精', '茂凯', '大树', 'ds', 'mk', 'nqsj', 'Maokai', 'niuqushujing', 'maokai',
                            'dashu'],
                     '58': ['荒漠屠夫', '鳄鱼', '雷克顿', 'ey', 'lkd', 'mmtf', 'huangmotufu', 'eyu', 'leikedun'],
                     '59': ['德玛西亚皇子', '嘉文四世', '皇子', '嘉文', 'JarvanIV', 'jw', 'hz', 'dmxyhz', 'jwss',
                            'demaxiyahuangzi', 'jiawensishi', 'huangzi', 'jiawen'],
                     '60': ['蜘蛛女皇', '伊莉丝', '蜘蛛', 'Elise', 'zz', 'zznh', 'yls', 'zhizhunvhuang', 'yilisi',
                            'zhizhu'],
                     '61': ['发条魔灵', '奥莉安娜', '发条', 'Orianna', 'ftml', 'ft', 'alan', 'fatiaomoling', 'aolianna',
                            'fatiao'],
                     '62': ['齐天大圣', '孙悟空', 'MonkeyKing', '猴子', 'hz', 'qtds', 'swk', 'qitiandasheng',
                            'sunwukong', 'houzi'],
                     '63': ['复仇焰魂', '布兰德', '火男', 'Brand', 'fuchouyanhun', 'bulande', 'huonan', 'cfyh', 'bld',
                            'hn'],
                     '64': ['盲僧', '瞎子', '李青', 'lq', 'xz', 'ms', 'LeeSin', 'mangseng', 'xiazi', 'liqing'],
                     '67': ['暗夜猎手', '薇恩', 'vn', 'Vayne', 've', 'ayls', 'anyelieshou', 'weien'],
                     '68': ['机械公敌', '兰博', 'Rumble', 'lb', 'jxgd', 'jixiegongdi', 'lanbo'],
                     '69': ['魔蛇之拥', '卡西奥佩娅', '蛇女', 'Cassiopeia', 'moshezhiyong', 'kaxiaopeiya', 'shenv',
                            'mszy', 'kxapy', 'sn'],
                     '72': ['水晶先锋', '斯卡纳', 'skn', 'sjxf', '蝎子', 'xz', 'Skarner', 'shuijingxianfeng', 'sikana',
                            'xiezi'],
                     '74': ['大发明家', '黑默丁格', '大头', 'Heimerdinger', 'dt', 'dfmj', 'hmdg', 'dafamingjia',
                            'heimodingge', 'datou'],
                     '75': ['沙漠死神', '内瑟斯', '狗头', 'gt', 'nss', 'smss', 'Nasus', 'shamosishen', 'neisesi',
                            'goutou'],
                     '76': ['狂野女猎手', '奈德丽', '豹女', 'bn', 'ndl', 'kynls', 'Nidalee', 'kuangyenvlieshou',
                            'naideli', 'baonv'],
                     '77': ['兽灵行者', '乌迪尔', 'Udyr', 'wde', 'slxz', 'UD', 'shoulingxingzhe', 'wudier'],
                     '78': ['圣锤之毅', '波比', 'bb', 'sczy', 'Poppy', 'shengchuizhiyi', 'bobi'],
                     '79': ['酒桶', '古拉加斯', '啤酒人', '肉蛋葱鸡', 'Gragas', 'pjr', 'jt', 'gljs', 'rdcj', 'jiutong',
                            'gulajiasi', 'pijiuren', 'roudancongji'],
                     '80': ['不屈之枪', '潘森', 'Pantheon', 'PS', 'bqzq', 'buquzhiqiang', 'pansen'],
                     '81': ['探险家', '伊泽瑞尔', 'ez', 'Ezreal', 'tanxianjia', 'yizeruier', 'txj', 'yzrr'],
                     '82': ['铁铠冥魂', '莫德凯撒', '铁男', 'Mordekaiser', 'tn', 'mdks', 'tkmh', 'tiekaiminghun',
                            'modekaisa', 'tienan'],
                     '83': ['牧魂人', '约里克', '掘墓人', 'jmr', 'mhr', 'ylk', 'Yorick', 'muhunren', 'yuelike',
                            'juemuren'], '84': ['阿卡丽', '离群之刺', 'akali', 'liqunzhici', 'akl', 'lqzc'],
                     '85': ['狂暴之心', '凯南', 'kn', 'kbzx', 'Kennen', 'kuangbaozhixin', 'kainan'],
                     '86': ['德玛西亚之力', '盖伦', '大宝剑', 'Garen', 'dbj', 'gl', 'dmxyzl', 'demaxiyazhili', 'gailun',
                            'dabaojian'],
                     '89': ['曙光女神', '蕾欧娜', '日女', '曙光', '女坦', 'nt', 'rn', 'sg', 'lon', 'sgns',
                            'shuguangnvshen', 'leiouna', 'rinv', 'shuguang', 'Leona', 'nvtan'],
                     '90': ['虚空先知', '玛尔扎哈', '蚂蚱', '马尔扎哈', 'Malzahar', 'mz', 'mezh', 'xkxz',
                            'xukongxianzhi', 'maerzhaha', 'mazha', 'maerzhaha'],
                     '91': ['刀锋之影', '男刀', '泰隆', 'tl', 'nd', 'dfzy', 'Talon', 'daofengzhiying', 'nandao',
                            'tailong'], '92': ['放逐之刃', '锐雯', 'Riven', 'rw', 'fzzr', 'fangzhuzhiren', 'ruiwen'],
                     '96': ['深渊巨口', '克格莫', '大嘴', 'KogMaw', 'dz', 'kgm', 'syjk', 'shenyuanjukou', 'kegemo',
                            'dazui'], '98': ['暮光之眼', '慎', 'yaozi', 's', 'mgzy', 'Shen', 'muguangzhiyan', 'shen'],
                     '99': ['光辉女郎', '拉克丝', '光辉', 'lux', 'lks', 'gh', 'ghnl', 'guanghuinvlang', 'lakesi',
                            'guanghui'],
                     '101': ['远古巫灵', '泽拉斯', 'guancaiban', 'gbc', 'zls', 'ygwl', 'Xerath', 'yuanguwuling',
                             'zelasi'],
                     '102': ['龙血武姬', '龙女', '希瓦娜', 'ln', 'xwn', 'lxwj', 'Shyvana', 'longxuewuji', 'longnv',
                             'xiwana'],
                     '103': ['九尾', '九尾妖狐', '狐狸', '阿狸', 'jiuwei', 'jiuweiyaohu', 'huli', 'ali', 'ahri', 'jwyh',
                             'al', 'hl', 'jw'],
                     '104': ['法外狂徒', '格雷福斯', '男枪', 'Graves', 'nq', 'glfs', 'fwkt', 'fawaikuangtu',
                             'geleifusi', 'nanqiang'],
                     '105': ['潮汐海灵', '菲兹', '小鱼人', 'Fizz', 'fz', 'xyr', 'cxhl', 'chaoxihailing', 'feizi',
                             'xiaoyuren'],
                     '106': ['不灭狂雷', '沃利贝尔', 'Volibear', '狗熊', 'gx', 'wlbe', 'bmkl', 'bumiekuanglei',
                             'wolibeier', 'gouxiong'],
                     '107': ['傲之追猎者', '狮子狗', '雷恩加尔', 'szg', 'leje', 'azzlz', 'Rengar', 'aozhizhuiliezhe',
                             'shizigou', 'leienjiaer'],
                     '110': ['惩戒之箭', '韦鲁斯', '维鲁斯', 'wls', 'cjzj', 'Varus', 'chengjiezhijian', 'weilusi'],
                     '111': ['深海泰坦', '诺提勒斯', '泰坦', 'Nautilus', 'tt', 'ntls', 'shtt', 'shenhaitaitan',
                             'nuotileisi', 'taitan'],
                     '112': ['机械先驱', '维克托', '三只手', 'szs', 'wkt', 'jxxq', 'Viktor', 'jixiexianqu', 'weiketuo',
                             'sanzhishou'],
                     '113': ['北地之怒', '猪妹', '瑟庄妮', 'zm', 'szn', 'bdzn', 'Sejuani', 'beidizhinu', 'zhumei',
                             'sezhuangni'],
                     '114': ['无双剑姬', '菲奥娜', '剑姬', 'Fiora', 'jj', 'wsjj', 'fan', 'wushuangjianji', 'feiaona',
                             'jianji'],
                     '115': ['爆破鬼才', '炸弹人', '吉格斯', 'Ziggs', 'jgs', 'zdr', 'bpgc', 'baopoguicai', 'zhadanren',
                             'jigesi'], '117': ['仙灵女巫', '璐璐', 'll', 'xlnw', 'Lulu', 'xianlingnvwu', 'lulu'],
                     '119': ['荣耀行刑官', '德莱文', 'Draven', 'rongyaoxingxingguan', 'delaiwen', 'ryxxg', 'dlw'],
                     '120': ['战争之影', '赫卡里姆', '人马', 'Hecarim', 'rm', 'zzzy', 'hlkm', 'zhanzhengzhiying',
                             'hekalimu', 'renma'],
                     '121': ['虚空掠夺者', '螳螂', '卡兹克', 'kzk', 'tl', 'xkldz', 'Khazix', 'xukonglueduozhe',
                             'tanglang', 'kazike'],
                     '122': ['诺克萨斯之手', '德莱厄斯', '诺手', 'Darius', 'nuokesasizhishou', 'delaiesi', 'nuoshou',
                             'nksszs', 'ns', 'dles'],
                     '126': ['未来守护者', '杰斯', 'Jayce', 'js', 'wlshz', 'weilaishouhuzhe', 'jiesi'],
                     '127': ['冰霜女巫', '冰女', '丽桑卓', 'Lissandra', 'bn', 'lsz', 'bsnw', 'bingshuangnvwu', 'bingnv',
                             'lisangzhuo'],
                     '131': ['皎月女神', '黛安娜', '皎月', 'Diana', 'jiaoyuenvshen', 'daianna', 'jiaoyue', 'jy', 'dan',
                             'jyns'],
                     '133': ['德玛西亚之翼', '奎因', '鸟人', 'ky', 'dmxyzz', 'Quinn', 'nr', 'demaxiyazhiyi', 'kuiyin',
                             'niaoren'],
                     '134': ['暗黑元首', '球女', '辛德拉', 'qn', 'xdl', 'ahyy', 'Syndra', 'anheiyuanshou', 'qiunv',
                             'xindela'],
                     '136': ['铸星龙王', '奥瑞利安索尔', '索尔', '龙王', 'AurelionSol', 'zhuxinglongwang',
                             'aoruiliansuoer', 'suoer', 'longwang', 'zxlw', 'lw', 'se', 'arlasr'],
                     '141': ['影流之镰', '凯隐', 'ky', 'ylzl', 'Kayn', 'yingliuzhilian', 'kaiyin'],
                     '142': ['暮光星灵', '佐伊', 'zy', 'mgxl', 'Zoe', 'muguangxingling', 'zuoyi'],
                     '143': ['荆棘之兴', '婕拉', 'jl', 'jjzx', 'Zyra', 'jingjizhixing', 'jiela'],
                     '145': ['虚空之女', '卡莎', 'ks', 'xkzn', 'Kaisa', 'xukongzhinv', 'kasha'],
                     '147': ['萨勒芬妮', '星籁歌姬', 'Seraphine', 'saleifenni', 'xinglaigeji'],
                     '150': ['迷失之牙', '纳尔', 'Gnar', 'ne', 'mszy', 'mishizhiya', 'naer'],
                     '154': ['生化魔人', '扎克', 'Zac', 'shenghuamoren', 'zhake', 'zk', 'shmr'],
                     '157': ['疾风剑豪', '剑豪', '亚索', 'Yasuo', 'ys', 'jh', 'jfjh', 'jifengjianhao', 'jianhao',
                             'yasuo'],
                     '161': ['虚空之眼', '大眼', '维克兹', 'wkz', 'dy', 'xkzy', 'Velkoz', 'xukongzhiyan', 'dayan',
                             'weikezi'],
                     '163': ['岩雀', '小鸟', '塔莉垭', 'tly', 'xn', 'yq', 'Taliyah', 'yanque', 'xiaoniao', 'taliya'],
                     '164': ['青钢影', '卡蜜尔', '卡密尔', 'Camille', '腿女', 'qinggangying', 'kamier', 'kamier',
                             'tuinv', 'qgy', 'kme', 'tn'],
                     '166': ['影哨', '阿克尚', '阿克', '阿', 'yingshao', 'akeshang', 'ake', 'a'],
                     '200': ['虚空女皇', 'Belveth', '卑尔维斯', 'xukongnvhuang', 'beierweisi'],
                     '201': ['弗雷尔卓德之心', '布隆', 'bl', 'Braum', 'flezdzx', 'fuleierzhuodezhixin', 'bulong'],
                     '202': ['戏命师', '烬', 'Jhin', 'j', 'xms', 'ximingshi', 'jin'],
                     '203': ['永猎双子', '千珏', 'Kindred', 'qj', 'ylsz', 'yonglieshuangzi', 'qianjue'],
                     '221': ['祖安花火', '泽丽', 'zeri', 'Zeri', 'zuanhuahuo', 'zeli'],
                     '222': ['暴走萝莉', '萝莉', '金克丝', 'Jinx', 'jks', 'll', 'bzll', 'baozouluoli', 'luoli',
                             'jinkesi', '金克丝'],
                     '223': ['河流之王', 'hama', '塔姆', 'tm', 'hlzw', 'TahmKench', 'heliuzhiwang', 'tamu'],
                     '233': ['贝蕾亚', 'beileiya', '狂', '蔷薇'],
                     '234': ['破败之王', '佛耶戈', '破败', '佛', 'pobaizhiwang', 'fuyege', 'pobai', 'fu'],
                     '235': ['涤魂圣枪', '赛娜', '奶枪', 'Senna', 'nq', 'sn', 'qhsq', 'dihunshengqiang', 'saina',
                             'naiqiang'],
                     '236': ['圣枪游侠', '卢锡安', '奥巴马', 'Lucian', 'abm', 'lxa', 'sqyx', 'shengqiangyouxia',
                             'luxian', 'aobama'], '238': ['影流之主', '劫', 'j', 'ylzz', 'Zed', 'yingliuzhizhu', 'jie'],
                     '240': ['暴怒骑士', '克烈', 'kl', 'bnqs', 'baonuqishi', 'kelie'],
                     '245': ['时间刺客', '艾克', 'Ekko', 'shijiancike', 'aike', 'ak', 'sjck'],
                     '246': ['元素女皇', '奇亚娜', 'qyn', 'ysnh', 'Qiyana', 'yuansunvhuang', 'qiyana'],
                     '254': ['皮城执法官', '拳女', '蔚', 'v', 'qv', 'pczfg', 'Vi', 'pichengzhifaguan', 'quannv', 'wei'],
                     '266': ['剑魔', '亚托克斯', '暗裔剑魔', 'jianmo', 'yatuokesi', 'anyijianmo', 'Aatrox', 'jm',
                             'ayjm', 'ytks'],
                     '267': ['唤潮鲛姬', '鲛姬', '娜美', 'nm', 'jj', 'hcjj', 'Nami', 'huanchaojiaoji', 'jiaoji',
                             'namei'],
                     '268': ['沙漠皇帝', '阿兹尔', '沙皇', 'Azir', 'shamohuangdi', 'azier', 'shahuang', 'smhd', 'aze',
                             'sh'],
                     '350': ['魔法猫咪', '猫', '猫咪', '悠米', 'cat', 'm', 'mm', 'mfmm', 'ym', 'Yuumi', 'mofamaomi',
                             'mao', 'maomi', 'youmi'],
                     '360': ['莎弥拉', '沙漠玫瑰', 'Samira', 'sml', 'smmg', 'shamila', 'shamomeigui'],
                     '412': ['魂锁典狱长', '锤石', 'Thresh', 'cs', 'hsdyz', 'hunsuodianyuzhang', 'chuishi'],
                     '420': ['海兽祭司', '俄洛伊', '触手妈', 'Illaoi', 'csm', 'ely', 'hsjs', 'haishoujisi', 'eluoyi',
                             'chushouma'],
                     '421': ['虚空遁地兽', '挖掘机', '雷克赛', '雷克塞', 'lks', 'wjj', 'xkdds', 'RekSai',
                             'xukongdundishou', 'wajueji', 'leikesai', 'leikesai'],
                     '427': ['翠神', '艾翁', '小菊', 'Ivern', 'xj', 'cs', 'aw', 'cuishen', 'aiweng', 'xiaoju'],
                     '429': ['复仇之矛', '卡莉丝塔', 'Kalista', 'fczm', 'klst', 'fuchouzhimao', 'kalisita'],
                     '432': ['星界游神', '巴德', 'Bard', 'xingjieyoushen', 'bade', 'xjys', 'bd'],
                     '497': ['幻翎', '洛', 'l', 'hl', 'Rakan', 'huanling', 'luo'],
                     '498': ['逆羽', '霞', 'x', 'ny', 'Xayah', 'niyu', 'xia'],
                     '516': ['山隐之焰', '奥恩', 'Ornn', 'an', 'syzy', 'shanyinzhiyan', 'aoen'],
                     '517': ['解脱者', '塞拉斯', 'sls', 'suannan', 'sn', 'jtz', 'Sylas', 'jietuozhe', 'sailasi'],
                     '518': ['万花通灵', '妮蔻', 'neeko', 'nk', 'whtl', 'wanhuatongling', 'nikou'],
                     '523': ['残月之肃', '厄斐琉斯', 'Aphelios', 'efls', 'cyzs', 'canyuezhisu', 'efeiliusi'],
                     '526': ['镕铁少女', '芮尔', '镕铁', 'rongtieshaonv', 'ruier', 'rongtie'],
                     '555': ['血港鬼影', '派克', 'pk', 'xggy', 'Pyke', 'xuegangguiying', 'paike'],
                     '711': ['薇古丝', '愁云使者', '熬夜波比', 'weigusi', 'chouyunshizhe', 'aoyebobi'],
                     '777': ['永恩', '封魔剑魂', 'ye', 'fmjh', 'Yone', 'yongen', 'fengmojianhun'],
                     '875': ['腕豪', '瑟提', 'jinfu', 'jf', 'Sett', 'st', 'wh', 'wanhao', 'seti'],
                     '876': ['含羞蓓蕾', '莉莉娅', '小鹿', 'lly', 'hxbl', 'Lillia', 'hanxiubeilei', 'liliya', 'xiaolu'],
                     '887': ['灵罗娃娃', '格温', '灵', '娃wa', 'gw', 'Gw', 'lingluowawa', 'gewen', 'ling', 'wa'],
                     '888': ['烈娜塔', '烈娜塔戈拉斯克', 'Renata', 'renata', '炼金男爵', 'lienata', 'lienatagelasike',
                             'lianjinnanjue'], '895': ['尼菈', '不羁之悦', 'Nilah', 'nila', 'bujizhiyue'],
                     '897': ['奎桑提', '纳祖芒荣耀', 'kuisangti', 'nazumangrongyao'],
                     '901': ['炽炎雏龙', '斯莫德', 'chiyanchulong', 'simode'],
                     '902': ['明烛', '米利欧', 'mingzhu', 'miliou'], '910': ['异画师', '彗', 'yihuashi', 'hui'],
                     '950': ['百裂冥犬', '纳亚菲利', 'bailiemingquan', 'nayafeili']}


def get_champion_keywords_by_id(champion_id):
    return CHAMPION_KEYWORDS[str(champion_id)]
